config/routes.rb
Rails.application.routes.draw do
  resources  :trainings
  resources  :admins
  resources  :score_cards
  devise_for :users

  root to: 'users#index'
end

app/models/training.rb
class Training < ActiveRecord::Base
	belongs_to :user

	has_many :trainee_enrollments,:dependent=>:destroy
	
	validates_presence_of :from ,:to
	validates_presence_of :course, :message=>"field can't be blank"

	scope :sorted,lambda {order("trainings.from DESC")}


	has_many :attendance_reports
	has_many :assignment_reports
	has_many :evaluation_reports

	
	has_many :observation_reports
	has_many :project_reports



	has_many :attendance_reports,:dependent=>:destroy
	has_many :assignment_reports,:dependent=>:destroy
	has_many :evaluation_reports,:dependent=>:destroy
	has_many :observation_reports,:dependent=>:destroy
	has_many :project_reports,:dependent=>:destroy

	def self.types
		['Foundation','Mandatory','Softskils','Functional','Technical']
	end


end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController


  def index

    @trainings= Training.paginate(:page => params[:page],:per_page => 6).order(from: :DESC)


    #current logged in user's emp id
    @user=User.find(current_user.id).employee_id
    @users=User.all



    #all trainings
    @tnrenrolls=TraineeEnrollment.all

    #all employees
    @employees=Employee.all

    #all departments
    @depts=Department.all

    #fetches all employees under the current logged user
    @emp=Employee.where("manager_id=?",@user)
  end


  

  def new
    @training=Training.new 
  end

  #creates training
  def create
    @training=Training.new(training_params)
    @user=User.where("employee_id=?",@training.trainer_id).first
     
    if @training.save

      @employee_name=Employee.find(@training.trainer_id).name
      @training.trainer_name=@employee_name

      @training.save

      UserMailer.training_email(@user).deliver
       redirect_to trainings_path
     else
       render('new')
     end
  end

  def edit
    @training=Training.find(params[:id])
  end


  #updates training
  def update
    flash[:notice]="training updated successfully"
    @training=Training.find(params[:id])
    if @training.update_attributes(training_params)
      redirect_to(trainings_path(:id=>@training.id))
    else
      #if update fails redirecting to the same page
      render('edit') 
    end
 end

  #doesnt delete it but gives the confirmation for deleting
  def delete
    @training=Training.find(params[:id])
  end
 
  #deletes the training from database for selected id  
  def destroy

    @training=Training.find(params[:id]).destroy
    redirect_to(:action=>'index')
  end
  
  #all methods under private are not actions anymore.
  private
  
  #whitelisting the attributes for trainings 
  def training_params
    params.require(:training).permit(:id,:course,:Type,:batchno,:trainer_id,:no_of_trainees,:trainees,:venue,:status,:from,:to)
 end

 def find_training
    @training=Training.find(params[:training_id])
  end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<!-- partial form for trainings --> 

<table id="update">
  <tr>
   <thead><th><%= f.label(:course) %></th></thead>
   <td ><%= f.text_field(:course) %></td>
 </tr>


 <tr>
   <th><%= f.label(:Type) %></th>
          <td><%= f.select(:Type,options_for_select([['Foundation','Foundation'], ['Mandatory','Mandatory'],[' Softskils','Softskils'],['Functional','Functional'],['Technical','Technical']],:Type))  %>
      </td>
 </tr>


 <tr>
   <th><%= f.label(:batchno) %></th>
          
   <td><%= f.text_field(:batchno) %></td>
    </td>
</tr>




<tr>
 <th><%= f.label(:trainerId) %></th>
        <%trainerlist%>
 <td>*lists only those who have an account</td>
   </td>
</tr>






<tr>
 <th><%= f.label(:venue) %></th>
     
 <td><%= f.text_field(:venue) %></td>
   </td>
</tr>



<tr>
 <th><%= f.label(:from) %></th>
        
 <td><%= f.date_field(:from) %></td>
   </td>
</tr>


<tr>
 <th><%= f.label(:to) %></th>
       <td><%= f.date_field(:to) %></td>

   </td>
</tr>
<tr>
  <td colspan="2" align="center">
   <%= submit_tag("update training ",:class=>'btn') %>

    </td>

</tr>


   	</table>

app/views/trainings/delete.html.erb
<!-- takes the particular id and delets it -->

<div align="center">
 <h2>Remove training</h2>

 <%= form_for(:training, :url => training_path,:method=>:delete) do |f| %>

   <p>Are you sure you want to permanently delete <%= @training.course %> training ?</p>
   <h1 class="fa fa-question-circle fa-4x"> </h1>
   

   <div>
     <%= button_tag("Remove training ",:class=>'hvr-shutter-in-vertical') %>
   </div>

 <% end %>
 <ul class="backlink">
  <li><%=link_to "back to training schedule", trainings_path,:class=>"hvr-icon-back"%></li>
</ul>
</div>

app/views/trainings/edit.html.erb
<!-- The Record is edited for particular training id --> 
	<div align="center">
	<h2 >Update Training</h2>
	<%= error_messages_for(@training) %>
	<%= form_for(:training,:url=>training_path(:id=>@training.id),:method=>:patch) do |f| %>
	<%= render(:partial=>"form",:locals=>{:f=>f}) %>
	<% end %>

	<ul class="backlink">
<li><%=link_to "back to training schedule", trainings_path,:class=>"hvr-icon-back"%></li>
</ul>
</div>

app/views/trainings/index.html.erb
<div align="center">
	<h2>Training Schedule</h2>
	<table>	
		<thead>
			<tr>
				<%if current_user_role=="Admin" || current_user_role=="Trainer"%>
					<th></th><!--the flash icon for new and updated records(only for admin and trainer) -->
				<%end%>
		    <th>Course</th>
				<th>Type</th>
				<th>Batch ID</th>                                       
				<th>Trainer ID</th>
				<th>Trainer</th>
				<th>Trainees</th>
				<th>Venue</th>
				<th>Status</th>
				<th>From</th>
				<th>To</th>
				<th>Actions</th>
			</tr>
		</thead>

		<!-- admin as user -->
	<%if User.find(current_user.id).role=="Admin"%>
		<% @trainings.each do |training| %>
		
			<tr>
			<%if training.created_at.to_date==Time.now.to_date%>
					<td><%= image_tag("new.gif", :alt => "new") %></td>
					<%elsif training.updated_at.to_date==Time.now.to_date%>
					<td><%= image_tag("updated.GIF", :alt => "updated") %></td>
					<%else%>
					<td></td>
					<%end%>
				<td><%= training.course %></td>
				<td><%= training.Type %></td>
				<% if !training.batchno || training.batchno==""%>
				<td>N/A</td>
				<%else%>
				<td><%= training.batchno %></td>
				<%end%>
				<td><%= training.trainer_id%></td>
				<td><%= training.trainer_name%></td>
        <td><%= TraineeEnrollment.where(:training_id=>training.id).count%></td>
				<td><%= training.venue %></td>
		        <td><%=training.status%></td>
				<td><%= training.from.strftime("%d-%b-%Y") %></td>
				<td><%= training.to.strftime("%d-%b-%Y") %></td>
		 		<td class="actions">
		 		<ul>
					<li><%= link_to("", edit_training_path(:id=>training.id),:title=>"Edit",:class=>"fa fa-pencil-square-o fa-2x ") %> </li>
					<li><%= link_to("",delete_training_path(training.id),:title=>"Delete",:class=>"fa fa-trash-o fa-2x") %> </li> 
					<li><%= link_to("",reports_path(training_id:training.id),:title=>"Reports",:class=>"fa fa-folder-open fa-2x") %></li> 
					<li><%= link_to("",tnrenrolls_path(training_id:training.id),:title=>"Trainees",:class=>"fa fa-user fa-2x")%></li>
				</ul>
			</td>
   		</tr>
		<%end%>
	<%end%>
	
	</table>
	<%= will_paginate @trainings %>

app/views/trainings/new.html.erb
<!-- it includes the javascript of trainings -->
<%= javascript_include_tag("trainings")%>
<div class="row">
  <div class="medium-2 large-3 columns"></div>
  <div class="medium-8 large-6 columns">
  <%= error_messages_for(@training) %> 
    <!-- redirects to training action -->
    <fieldset class="fieldset">
    <legend>Create Training</legend>
    <%= form_for(:training,:url=>{:action=>'create'},html: {'data-abide': true, 'novalidate': true}) do |f| %>
    <div data-abide-error class="alert callout" style="display: none;">
      <p><i class="fi-alert"></i> There are some errors in your form.</p>
    </div>
    <table class="hover unstriped stack">
	    <tr>
		    <th><%= f.label(:course) %></th>
        <td>
          <%= f.text_field(:course,required: true) %>
          <span class="form-error">course name is required</span>
        </td>
		  </tr>
      <tr>
        <th><%= f.label(:Type) %></th>
        <td><%= f.select :Type,options_for_select(Training.types) %>
      </tr>
      <tr>
        <th><%= f.label(:batchno) %></th>       
        <td>
          <%= f.number_field(:batchno,required:true) %>
          <span class="form-error">Batch.no is required</span>
        </td>
      </tr>       
      <tr>
        <th>Trainer</th>
          <%trainerlist%>
        <td>*lists only those who have an account</td>
      </tr>
      <tr>
        <th><%= f.label(:venue) %></th>
        <td><%= f.text_field(:venue) %></td>
      </tr>
      <tr>
        <th><%= f.label(:status) %></th>      
        <td><%=f.select :status ,options_for_select([["Created"]])%></td>
      </tr>
      <tr>
        <th><%= f.label(:from) %></th>         
        <td><%= f.date_field(:from,:value=>Time.now.strftime("%Y-%m-%d")) %></td>
      </tr>
      <tr>
        <th><%= f.label(:to) %></th>
        <td><%= f.date_field(:to,:value=>Time.now.strftime("%Y-%m-%d")) %></td>
      </tr>
      <tr>
        <td colspan="2" align="center"><%= submit_tag("create training",:class=>"btn") %></td>
      </tr>
  </table>
  <% end %>
  </fieldset>
  <%=link_to "back to training schedule", trainings_path,:class=>"hvr-icon-back"%>
  </div>
  <div class="medium-2 large-3 columns"></div>
  </div>