config/routes.rb
Rails.application.routes.draw do
  resources  :trainings
  resources  :admins
  resources  :score_cards
  devise_for :users

  root to: 'users#index'
end

app/models/score.rb
class Score < ActiveRecord::Base
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  before_action :checkadmin, except: [:show]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:gui, :timeline, :time_space, :logic, :code_convention, :use_technology, :tools_usage, :presentation,:Time_space_effeciency,:code_optimization,:meeting_timelines,:code_integrity,:knowledge,:format_submission)
    end

    def checkadmin
        if User.find(current_user.id).role=="Admin"
            
        else 
            flash[:notice] = "illegal access attempted, auto logout"
            sign_out current_user
            redirect_to(user_session_path)
        end

    end
end

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
 <table id="update">
  <tr>
   <th> <%= f.label :gui %></th>
    <td><%= f.text_field :gui %></td>
  </tr>
<tr>
    <th><%= f.label :timeline %></th>
    <td><%= f.text_field :timeline %></td>
  </tr>
  <tr>
    <th><%= f.label :time_space %><th>
    <td><%= f.text_field :time_space %></td>
  </tr>
 <tr>
    <th> <%= f.label :logic %></th>
    <td><%= f.text_field :logic %></td>
  </tr>
 <tr>
     <th><%= f.label :code_convention %></th>
    <td><%= f.text_field :code_convention %></td>
  </tr>
<tr>
    <th> <%= f.label :use_technology %></th>
    <td><%= f.text_field :use_technology %></td>
  </tr>
<tr>
    <th> <%= f.label :tools_usage %></th>
     <td><%= f.text_field :tools_usage %></td>
  </tr>
<tr>
     <th><%= f.label :presentation %></th>
     <td><%= f.text_field :presentation %></td>
  </tr>
 <tr>
     <th><%= f.label :Time_space_effeciency %></th>
     <td><%= f.text_field :Time_space_effeciency %></td>
  </tr>
 <tr>
     <th><%= f.label :code_optimization %></th>
     <td><%= f.text_field :code_optimization %></td>
 </tr>
<tr>
     <th><%= f.label :meeting_timelines %></th>
     <td><%= f.text_field :meeting_timelines %></td>
  </tr>
 <tr>
     <th><%= f.label :code_integrity %></th>
     <td><%= f.text_field :code_integrity %></td>
  </tr>
<tr>
     <th><%= f.label :knowledge %></th>
     <td><%= f.text_field :knowledge %></td>
  </tr>
  <tr>
     <th><%= f.label :format_submission %></th>
     <td><%= f.text_field :format_submission %></td>
 </tr>
<tr>
    <%= f.submit ,:class=>"btn"%>
</tr>
<% end %>
</table>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>
<div align="center">
<h1>Editing score</h1>

<%= render(:partial=>"form") %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>
</div>

app/views/scores/index.html.erb
<h1>Listing scores</h1>

<table id="table">

<div align="center">
<h1>Listing scores</h1>

<table id="table" align="center">

  <thead>
    <tr>
      <th>Gui</th>
      <th>Timeline</th>
      <th>Time space</th>
      <th>Logic</th>
      <th>Code convention</th>
      <th>Use technology</th>
      <th>Tools usage</th>
      <th>Presentation</th>
      <th>Time space effeciency</th>
      <th>Code optimization</th>
      <th>Meeting timelines</th>
      <th>Code integrity</th>
      <th>Knowledge</th>
      <th>Format submission</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.gui %></td>
        <td><%= score.timeline %></td>
        <td><%= score.time_space %></td>
        <td><%= score.logic %></td>
        <td><%= score.code_convention %></td>
        <td><%= score.use_technology %></td>
        <td><%= score.tools_usage %></td>
        <td><%= score.presentation %></td>
        <td><%= score.Time_space_effeciency %></td>
        <td><%= score.code_optimization %></td>
        <td><%= score.meeting_timelines %></td>
        <td><%= score.code_integrity %></td>
        <td><%= score.knowledge %></td>
        <td><%= score.format_submission %></td>
        <td><%= link_to '', edit_score_path(score,:title=>"Edit",:class=>"fa fa-pencil-square-o fa-2x ") %></td>
        <td><%= link_to '', score, method: :delete,:title=>"Delete",:class=>"fa fa-trash-o fa-2x", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

<%if Score.all.count<1%>
<li><%= link_to("Add score",new_score_path,:class=>"reports",:class=>"hvr-icon-float-away") %></li> 
<%end%>
</div>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= link_to 'Back', scores_path %>
<div align="center">
<h1>New score</h1>

<%= render(:partial=>"form") %>

<%= link_to 'Back', scores_path %>
</div>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gui:</strong>
  <%= @score.gui %>
</p>

<p>
  <strong>Timeline:</strong>
  <%= @score.timeline %>
</p>

<p>
  <strong>Time space:</strong>
  <%= @score.time_space %>
</p>

<p>
  <strong>Logic:</strong>
  <%= @score.logic %>
</p>

<p>
  <strong>Code convention:</strong>
  <%= @score.code_convention %>
</p>

<p>
  <strong>Use technology:</strong>
  <%= @score.use_technology %>
</p>

<p>
  <strong>Tools usage:</strong>
  <%= @score.tools_usage %>
</p>

<p>
  <strong>Presentation:</strong>
  <%= @score.presentation %>
</p>

<p>
  <strong>Time space effeciency:</strong>
  <%= @score.Time_space_effeciency %>
</p>

<p>
  <strong>Code optimization:</strong>
  <%= @score.code_optimization %>
</p>

<p>
  <strong>Meeting timelines:</strong>
  <%= @score.meeting_timelines %>
</p>

<p>
  <strong>Code integrity:</strong>
  <%= @score.code_integrity %>
</p>

<p>
  <strong>Knowledge:</strong>
  <%= @score.knowledge %>
</p>

<p>
  <strong>Format submission:</strong>
  <%= @score.format_submission %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |

<%= link_to 'Back', scores_path %>