config/routes.rb
Rails.application.routes.draw do
  resources  :trainings
  resources  :admins
  resources  :score_cards
  devise_for :users

  root to: 'users#index'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	#carrying training ID to reports index to have reports of a particular ID

	def index
		@training=Training.find(params[:training_id])
	end

	#this action is not yet implemented
	#def allreports

		#if params[:reporttype]=="attendances"
			#@from=params[:from] if params[:from].present?
			#@to=params[:to]	if params[:to].present?	
			#@search =AttendanceReport.where("STR_TO_DATE(date, '%m-%d-%Y')BETWEEN ? AND ?",@from,@to).search do
				#fulltext params[:name]
				#paginate :page => params[:page],:per_page=>8
		 	#end
				#@attendances=@search.results
		#end
 #end
end

app/views/reports/index.html.erb
<div align="center">



<%if @training.Type=="Foundation" %>
<ul class='reportlinks'>
<li><h2><%=@training.course%> Reports</h2></li>
<li><%=link_to("Attendance Report",attendances_path(:training_id=>@training.id),:class=>"hvr-bounce-to-top ")%> </li>
<li><%=link_to("Observation Report",observations_path(:training_id=>@training.id),:class=>"hvr-bounce-to-top ")%></li>
</ul>

<ul class='reportlinks'>
<li><%=link_to("Evaluation Report",evaluations_path(training_id:@training.id),:class=>"hvr-bounce-to-top ")%> </li>
<li><%=link_to("Assignment Report",assignments_path(:training_id=>@training.id),:class=>"hvr-bounce-to-top ")%> </li>
</ul>
<ul class='reportlinks'>
<li><%=link_to("Project Report",projects_path(:training_id=>@training.id),:class=>"hvr-bounce-to-top ")%> </li>
</ul>
<%end%>




<%if @training.Type=="Mandatory"%>
<ul class='reportlinks'>
<li><h1><%=@training.course%></h1></li>
<li><%=link_to("Attendance Report",attendances_path(:training_id=>@training.id),:class=>"hvr-bounce-to-top")%></li>
<li><%=link_to("Evaluation Report",evaluations_path(training_id:@training.id),:class=>"hvr-bounce-to-top ")%> </li>
</ul>
<%end%>
<%if @training.Type=="Softskils"%>
<ul class='reportlinks'>
<li><h1><%=@training.course%></h1></li>
<li><%=link_to("Attendance Report",attendances_path(:training_id=>@training.id),:class=>"hvr-bounce-to-top")%></li>
<li><%=link_to("Evaluation Report",evaluations_path(training_id:@training.id),:class=>"hvr-bounce-to-top ")%> </li>
</ul>
<%end%>


 
<%if @training.Type=="Functional"%>
<ul class='reportlinks'>
<li><h1><%=@training.course%></h1></li>
<li><%=link_to("Attendance Report",attendances_path(:training_id=>@training.id),:class=>"hvr-bounce-to-top")%></li>
<li><%=link_to("Evaluation Report",evaluations_path(training_id:@training.id),:class=>"hvr-bounce-to-top ")%> </li>
</ul>
<%end%>


<%if @training.Type=="Technical"%>
<ul class='reportlinks'>
<li><h1><%=@training.course%></h1></li>
<li><%=link_to("Attendance Report",attendances_path(:training_id=>@training.id),:class=>"hvr-bounce-to-top")%></li>
<li><%=link_to("Evaluation Report",evaluations_path(training_id:@training.id),:class=>"hvr-bounce-to-top ")%> </li>
</ul>
<%end%>



<ul class='backlink'>
<li><%=link_to "back to training schedule", trainings_path,:class=>"hvr-icon-back"%></li>
</ul>
</div>

  